# app/routers/ocean_routes.py
from fastapi import APIRouter, Query
from fastapi.responses import Response
import matplotlib.pyplot as plt
import pandas as pd
import io
from app.database import supabase

router = APIRouter(prefix="/ocean", tags=["Ocean Visualization"])


# ============================
# VALID FIELDS
# ============================
Y_PARAMETERS = [
    "dic", "mld", "pco2_original", "chl",
    "no3", "sss", "sst", "deviant_uncertainty"
]

X_OPTIONS = ["lat", "lon", "datetime"]


# ============================
# UNITS (as per your dataset)
# ============================

UNITS = {
    "dic": "milimole/m3",
    "mld": "m",
    "pco2_original": "micro_atm",
    "chl": "kg/m3",
    "no3": "milimole/m3",
    "sss": "PSU",
    "sst": "deg C",
    "deviant_uncertainty": "micro atm"
}


# ============================
# RANGE LIMITS (scientific)
# ============================

RANGE_LIMITS = {
    "dic": (1950, 2100),
    "mld": (0, 100),
    "pco2_original": (250, 550),
    "chl": (5e-8, 4e-7),
    "no3": (0.00, 0.06),
    "sss": (30, 40),
    "sst": (20, 35),
    "deviant_uncertainty": (0, 5)
}


# ============================
# DB LOADER
# ============================

def load_ocean_data():
    res = supabase.table("ocean_data").select("*").execute()
    if not res.data:
        return None

    df = pd.DataFrame(res.data)

    # convert datetime
    if "datetime" in df.columns:
        df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")

    return df



# ============================
# MAIN PLOT ENDPOINT
# ============================

@router.get("/plot")
def generate_plot(
    plot_type: str = Query(..., enum=["line", "scatter", "bubble"]),
    x: str = Query(..., enum=X_OPTIONS),
    y: str = Query(..., enum=Y_PARAMETERS),
    start_date: str | None = None,
    end_date: str | None = None
):
    df = load_ocean_data()
    if df is None:
        return {"error": "No ocean data available"}

    # ----- Filter by date range -----
    if x == "datetime":
        if start_date:
            df = df[df["datetime"] >= pd.to_datetime(start_date)]
        if end_date:
            df = df[df["datetime"] <= pd.to_datetime(end_date)]

    # Keep only required columns
    df = df[[x, y]].dropna()

    if df.empty:
        return {"error": "No data available for selected parameters"}

    # ----- Prepare ranges -----
    ymin, ymax = RANGE_LIMITS.get(y, (df[y].min(), df[y].max()))
    unit = UNITS.get(y, "")

    # ==========================================================
    # BEAUTIFIED OUTPUT — PREMIUM LOOK FOR JUDGES (ONLY ADDED)
    # ==========================================================

    plt.figure(figsize=(12, 6), dpi=180)
    plt.style.use("seaborn-v0_8")

    ax = plt.gca()
    ax.set_facecolor("#f7f9fc")   # soft background
    plt.grid(color="#d9d9d9", linestyle="--", linewidth=0.7, alpha=0.7)

    # ======= ORIGINAL PLOT LOGIC (NOT CHANGED) =======
    if plot_type == "line":
        plt.plot(
            df[x], df[y],
            linewidth=2.2,
            color="#2962FF",
            label=f"{y.upper()} ({unit})"
        )

    elif plot_type == "scatter":
        plt.scatter(
            df[x], df[y],
            s=45,
            color="#2962FF",
            edgecolor="#1a1a1a",
            alpha=0.85,
            label=f"{y.upper()} ({unit})"
        )

    # Bubble plot (future use)
    elif plot_type == "bubble":
        plt.scatter(
            df[x], df[y],
            s=60,
            alpha=0.70,
            color="#009688",
            edgecolor="#00332f",
            label=f"{y.upper()} ({unit})"
        )

    # =====================================================
    # PREMIUM LEGEND, LABELS, TITLES, WATERMARK
    # =====================================================

    plt.title(
        f"{plot_type.upper()} plot of {y.upper()} vs {x.upper()}",
        fontsize=18,
        fontweight="bold",
        pad=20,
        color="#0a0a0a"
    )

    plt.xlabel(x.upper(), fontsize=14, fontweight="bold")
    plt.ylabel(f"{y.upper()} ({unit})", fontsize=14, fontweight="bold")

    plt.ylim(ymin, ymax)

    plt.legend(
        fontsize=12,
        loc="upper right",
        frameon=True,
        facecolor="#ffffff",
        edgecolor="#cccccc"
    )

    plt.text(
        0.99, 0.01,
        "Generated by CMFRI Ocean Analytics",
        fontsize=10,
        color="#777777",
        ha="right",
        va="bottom",
        alpha=0.8,
        transform=plt.gca().transAxes,
    )

    plt.tight_layout()

    # ----- Return PNG -----
    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=180)
    plt.close()
    buf.seek(0)

    return Response(content=buf.getvalue(), media_type="image/png")
