# app/routers/ocean_routes.py
from fastapi import APIRouter, Query
from fastapi.responses import Response
import matplotlib.pyplot as plt
import pandas as pd
import io
from app.database import supabase

router = APIRouter(prefix="/ocean", tags=["Ocean Visualization"])


# ============================
# VALID FIELDS
# ============================
Y_PARAMETERS = [
    "dic", "mld", "pco2_original", "chl",
    "no3", "sss", "sst", "deviant_uncertainty"
]

X_OPTIONS = ["lat", "lon", "datetime"]


# ============================
# UNITS (as per your dataset)
# ============================

UNITS = {
    "dic": "milimole/m3",
    "mld": "m",
    "pco2_original": "micro_atm",
    "chl": "kg/m3",
    "no3": "milimole/m3",
    "sss": "PSU",
    "sst": "deg C",
    "deviant_uncertainty": "micro atm"
}


# ============================
# RANGE LIMITS (scientific)
# ============================

RANGE_LIMITS = {
    "dic": (1950, 2100),
    "mld": (0, 100),
    "pco2_original": (250, 550),
    "chl": (5e-8, 4e-7),
    "no3": (0.00, 0.06),
    "sss": (30, 40),
    "sst": (20, 35),
    "deviant_uncertainty": (0, 5)
}


# ============================
# DB LOADER
# ============================

def load_ocean_data():
    res = supabase.table("ocean_data").select("*").execute()
    if not res.data:
        return None

    df = pd.DataFrame(res.data)

    # convert datetime
    if "datetime" in df.columns:
        df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")

    return df



# ============================
# MAIN PLOT ENDPOINT
# ============================

@router.get("/plot/multi")
def generate_multi_plot(
    plot_type: str = Query(..., enum=["line", "scatter"]),
    x: str = Query(..., enum=X_OPTIONS),
    params: list[str] = Query(..., description="Select multiple Y parameters (up to 8)"),
    start_date: str | None = None,
    end_date: str | None = None
):
    df = load_ocean_data()
    if df is None:
        return {"error": "No ocean data available"}

    # ---- Date filter if datetime on x ----
    if x == "datetime":
        if start_date:
            df = df[df["datetime"] >= pd.to_datetime(start_date)]
        if end_date:
            df = df[df["datetime"] <= pd.to_datetime(end_date)]

    # ---- Validate Y parameters ----
    invalid = [p for p in params if p not in Y_PARAMETERS]
    if invalid:
        return {"error": f"Invalid parameters: {invalid}"}

    # keep valid columns
    keep_cols = [x] + params
    df = df[keep_cols].dropna()
    if df.empty:
        return {"error": "No data available for selected parameters"}

    # ==============================================
    # PREMIUM STYLING (kept same as your original)
    # ==============================================
    plt.figure(figsize=(12, 6), dpi=180)
    plt.style.use("seaborn-v0_8")
    ax = plt.gca()
    ax.set_facecolor("#f7f9fc")
    plt.grid(color="#d9d9d9", linestyle="--", linewidth=0.7, alpha=0.7)

    COLORS = [
        "#2962FF", "#009688", "#F57C00", "#C51162",
        "#4A148C", "#1B5E20", "#D50000", "#6A1B9A"
    ]

    # ==============================================
    # MULTI-PARAMETER LOOP
    # ==============================================
    for idx, param in enumerate(params):
        y = df[param]
        unit = UNITS.get(param, "")
        ymin, ymax = RANGE_LIMITS.get(param, (y.min(), y.max()))
        color = COLORS[idx % len(COLORS)]

        if plot_type == "line":
            plt.plot(
                df[x], y,
                linewidth=2.2,
                color=color,
                label=f"{param.upper()} ({unit})"
            )

        elif plot_type == "scatter":
            plt.scatter(
                df[x], y,
                s=45,
                color=color,
                edgecolor="#1a1a1a",
                alpha=0.85,
                label=f"{param.upper()} ({unit})"
            )

    # ==============================================
    # Titles, labels, legend
    # ==============================================
    plt.title(
        f"{plot_type.upper()} Comparison Plot for Multiple Parameters",
        fontsize=18,
        fontweight="bold",
        pad=20,
        color="#0a0a0a"
    )

    plt.xlabel(x.upper(), fontsize=14, fontweight="bold")
    plt.ylabel("Parameter Values", fontsize=14, fontweight="bold")

    # no global limit, each line uses own limit for display clarity

    plt.legend(
        fontsize=11,
        loc="best",
        frameon=True,
        facecolor="#ffffff",
        edgecolor="#cccccc"
    )

    plt.text(
        0.99, 0.01,
        "Generated by CMFRI Ocean Analytics",
        fontsize=10,
        color="#777777",
        ha="right",
        va="bottom",
        alpha=0.8,
        transform=plt.gca().transAxes
    )

    plt.tight_layout()

    # ----- Return PNG -----
    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=200)
    plt.close()
    buf.seek(0)

    return Response(content=buf.getvalue(), media_type="image/png")
